# app/schemas.py

# pydantic models define the shape of data coming in and going out of the API
# they handle validation automatically — if a required field is missing,
# FastAPI returns a clear error instead of crashing
from pydantic import BaseModel
from typing import Optional
from datetime import datetime

# --- Webtoon schemas ---

class WebtoonCreate(BaseModel):
    # fields required when creating a new webtoon
    title: str
    author: str
    genre: Optional[str] = None
    cover_url: Optional[str] = None
    description: Optional[str] = None

class WebtoonResponse(BaseModel):
    # fields returned when reading a webtoon from the database
    # includes id and created_at which are generated by the db
    id: int
    title: str
    author: str
    genre: Optional[str]
    cover_url: Optional[str]
    description: Optional[str]
    created_at: datetime

    class Config:
        # allows pydantic to read data from SQLAlchemy model objects
        # without this, pydantic can only read plain dicts
        from_attributes = True

# --- Review schemas ---

class ReviewCreate(BaseModel):
    webtoon_id: int
    rating: int           # must be 1-5, validated in the router
    content: Optional[str] = None
    status: str = "reading"

class ReviewResponse(BaseModel):
    id: int
    webtoon_id: int
    rating: int
    content: Optional[str]
    status: str
    created_at: datetime

    class Config:
        from_attributes = True